# Generated by Django 3.1.7 on 2021-02-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20210228_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='token',
            old_name='name',
            new_name='title',
        ),
    ]
