# Generated by Django 3.1.7 on 2021-04-11 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0004_auto_20210313_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='account',
        ),
        migrations.AddField(
            model_name='token',
            name='profiles',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
