# Generated by Django 3.2 on 2021-04-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_auto_20210411_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='profiles',
            new_name='accounts',
        ),
    ]
